@hostname = https://localhost
@port = 5001
@host = {{hostname}}:{{port}}

###

GET {{host}}/api/races/4/entries

###

GET {{host}}/api/races/4/entries/1

###

POST {{host}}/api/races/4/entries
Content-Type: application/json

{
  "RaceId": 4,
  "RiderId": 2
}