@hostname = https://localhost
@port = 5001
@host = {{hostname}}:{{port}}

###

GET {{host}}/api/races/2/entries

###

GET {{host}}/api/races/2/entries/2

###

POST {{host}}/api/races/2/entries
Content-Type: application/json

{
  "RaceId": 2,
  "RiderId": 3
}